In [8]:
# Dot product
#Big Data Example (User–Movie Recommendation System)
#✔ 5 Users
#✔ 6 Movies
#✔ 3 Features (Action, Comedy, Drama)

In [9]:
import numpy as np

In [10]:
#User preference matrics(5 users, 3 preferance)
A=np.array([

[4,1,2],
[2,5,1],
[1,1,5],
[3,4,2],
[5,0,1],
])
#Movie preference matris(6 movies, 3 feautures)
B=np.array([
    [5,0,3],
    [1,5,0],
    [2,1,4],
    [4,3,1],
    [0,4,5],
    [3,2,2],
])
Scores=np.dot(A,B.T)
print(Scores)

[[26  9 17 21 14 18]
 [13 27 13 24 25 18]
 [20  6 23 12 29 15]
 [21 23 18 26 26 21]
 [28  5 14 21  5 17]]


In [11]:
#Music Streaming Platform – Sample Practice Data
#User Preference Matrix (8 users × 4 features)
Users=np.array([
    [5, 2, 1, 3],   # User 1
    [1, 4, 3, 2],   # User 2
    [3, 5, 0, 1],   # User 3
    [2, 1, 4, 5],   # User 4
    [4, 0, 2, 3],   # User 5
    [0, 3, 5, 1],   # User 6
    [2, 4, 1, 0],   # User 7
    [5, 1, 0, 4]    # User 8
])
#Song Feature Matrix (10 songs × 4 features)
songs = np.array([
    [4, 3, 0, 2],   # Song 1
    [1, 5, 2, 0],   # Song 2
    [3, 0, 4, 1],   # Song 3
    [5, 2, 1, 3],   # Song 4
    [0, 4, 5, 1],   # Song 5
    [2, 1, 3, 4],   # Song 6
    [4, 0, 2, 5],   # Song 7
    [1, 3, 0, 4],   # Song 8
    [3, 2, 5, 0],   # Song 9
    [0, 1, 4, 3]    # Song 10
])
Scores=np.dot(Users,songs.T)
print(Scores)


[[32 17 22 39 16 27 37 23 24 15]
 [20 27 17 22 33 23 20 21 26 22]
 [29 28 10 28 21 15 17 22 19  8]
 [21 15 27 31 29 37 41 25 28 32]
 [22  8 23 31 13 26 35 16 22 17]
 [11 25 21 14 38 22 15 13 31 26]
 [20 24 10 19 21 11 10 14 19  8]
 [31 10 19 39  8 27 40 24 17 13]]


In [12]:
# CUMULATIVE PRODUCT.NP.CUMPROD()
#quantity = [5, 3, 2, 4, 6, 2, 3, 5, 4, 2,
           # 7, 3, 2, 5, 4, 3, 6, 2, 3, 4]
A=np.array( [5, 3, 2, 4, 6, 2, 3, 5, 4, 2,
            7, 3, 2, 5, 4, 3, 6, 2, 3, 4]
)
print(np.cumprod(A))


[          5          15          30         120         720        1440
        4320       21600       86400      172800     1209600     3628800
     7257600    36288000   145152000   435456000  2612736000  5225472000
 15676416000 62705664000]


In [13]:
#cumulative sum. np.cumsum()
A=np.array([120, 150, 180, 200, 90, 160, 170, 140, 220, 190,
         130, 145, 155, 210, 175, 165, 185, 195, 205, 135,
         125, 140, 160, 180, 200, 190, 170, 160, 150, 140])
print(np.cumsum(A))

[ 120  270  450  650  740  900 1070 1210 1430 1620 1750 1895 2050 2260
 2435 2600 2785 2980 3185 3320 3445 3585 3745 3925 4125 4315 4485 4645
 4795 4935]


In [14]:
#index of maximum elements. np.argmax()
A=np.array([
    12000, 13500, 12800, 15000, 14200, 16000,
    15500, 14800, 17000, 16500, 15800, 17500,
    18000, 17200, 16900, 19000, 18800, 18500,
    19500, 17800, 18200, 20000, 19800, 19200
])
print(np.argmax(A))

21


In [15]:
#np.clip
A=np.array([
    12, 18, 25, 42, 39, 10, 33, 28, 45, 37,
    16, 14, 20, 22, 48, 30, 32, 11, 27, 35,
    13, 19, 21, 50, 41, 29, 17, 26, 24, 38,
    46, 15, 23, 40, 12, 31, 34, 43, 36, 18,
    14, 29, 47, 20, 22, 39, 41, 13, 27, 35
])
print(np.clip(A,19,35))

[19 19 25 35 35 19 33 28 35 35 19 19 20 22 35 30 32 19 27 35 19 19 21 35
 35 29 19 26 24 35 35 19 23 35 19 31 34 35 35 19 19 29 35 20 22 35 35 19
 27 35]


In [16]:
# power values values
A=np.array([
    2, 5, 7, 3, 6, 8, 4, 9, 10, 12,
    11, 13, 14, 16, 15, 18, 20, 22, 24, 26,
    28, 30, 32, 3, 5, 7, 9, 11, 13, 15,
    17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
    37, 39, 41, 43, 45, 47, 49, 50, 52, 54
])
print(np.power(A,2))
print(np.power(A,3))

[   4   25   49    9   36   64   16   81  100  144  121  169  196  256
  225  324  400  484  576  676  784  900 1024    9   25   49   81  121
  169  225  289  361  441  529  625  729  841  961 1089 1225 1369 1521
 1681 1849 2025 2209 2401 2500 2704 2916]
[     8    125    343     27    216    512     64    729   1000   1728
   1331   2197   2744   4096   3375   5832   8000  10648  13824  17576
  21952  27000  32768     27    125    343    729   1331   2197   3375
   4913   6859   9261  12167  15625  19683  24389  29791  35937  42875
  50653  59319  68921  79507  91125 103823 117649 125000 140608 157464]


In [17]:
# caluculating square root value
A=np.array([
    4, 9, 16, 25, 36, 49, 64, 81, 100, 121,
    144, 169, 196, 225, 256, 289, 324, 361, 400, 441,
    484, 529, 576, 625, 676, 729, 784, 841, 900, 961,
    1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681,
    1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601
])
print(np.sqrt(A))


[ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19.
 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36. 37.
 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51.]


In [18]:
# Swap rows and columns.
A=np.array([
    [120, 150, 180, 200, 175, 160, 210, 195],
    [135, 140, 155, 165, 170, 185, 190, 200],
    [110, 125, 145, 155, 160, 175, 180, 190],
    [100, 130, 150, 170, 160, 140, 135, 145],
    [140, 155, 165, 175, 185, 195, 205, 215],
    [125, 135, 145, 155, 165, 175, 185, 195]
])
print(A.T)

[[120 135 110 100 140 125]
 [150 140 125 130 155 135]
 [180 155 145 150 165 145]
 [200 165 155 170 175 155]
 [175 170 160 160 185 165]
 [160 185 175 140 195 175]
 [210 190 180 135 205 185]
 [195 200 190 145 215 195]]


In [19]:
# Flatten to 1D.np.ravel()
A=np.array([
    [12, 15, 18, 20, 17, 19, 22, 24, 21, 23],
    [14, 16, 19, 21, 18, 20, 23, 25, 22, 24],
    [11, 13, 15, 17, 19, 21, 20, 22, 23, 25],
    [10, 12, 14, 16, 18, 17, 19, 21, 20, 22],
    [13, 15, 17, 19, 21, 23, 22, 24, 26, 28]
])
print(np.ravel(A))

[12 15 18 20 17 19 22 24 21 23 14 16 19 21 18 20 23 25 22 24 11 13 15 17
 19 21 20 22 23 25 10 12 14 16 18 17 19 21 20 22 13 15 17 19 21 23 22 24
 26 28]


In [20]:
#np.eye()
A=np.eye(11)
print(A)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [21]:
#np.full()
A=np.full((6,6),66)
print(A)

[[66 66 66 66 66 66]
 [66 66 66 66 66 66]
 [66 66 66 66 66 66]
 [66 66 66 66 66 66]
 [66 66 66 66 66 66]
 [66 66 66 66 66 66]]


In [28]:
# Create a NumPy array from 10 to 50 and find shape, size, and dimensions.
A=np.arange(7,70)
print("Array:", A)
print("shape:", A.shape)
print("sie:", A.size)
print("Dimensions:", A.ndim)

Array: [ 7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30
 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54
 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]
shape: (63,)
sie: 63
Dimensions: 1


In [29]:
# Random numbers
A=np.random.randint(20,40,4)
print(A)

[33 36 37 36]


In [30]:
#Unique Values
A = np.array([7, 7, 7, 7, 2, 2, 2, 9, 9, 5, 5, 5, 5, 5, 1, 1])
print(np.unique(A))


[1 2 5 7 9]


In [32]:
#Concatenate Arrays
b1 = np.array([10, 20])
b2 = np.array([30, 40, 50, 60])
print(np.concatenate((b1,b2)))

[10 20 30 40 50 60]


In [33]:
#Element-wise Comparison
A = np.array([
    120, 135, 99, 150, 210, 175, 199, 250, 300, 275,
    89, 95, 110, 130, 140, 160, 170, 180, 190, 220,
    260, 280, 290, 310, 330, 350, 370, 390, 410, 430,
    100, 115, 125, 145, 155, 165, 185, 205, 225, 245,
    265, 285, 295, 315, 335, 355, 375, 395, 415, 435
])
print(A>=150)


[False False False  True  True  True  True  True  True  True False False
 False False False  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True False False False False  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True]


In [35]:
#Sum / Min / Max
sales = np.array([
    [1200, 1350, 1400, 1500, 1600, 1700, 1550, 1620, 1580, 1490, 1300, 1280, 1250, 1400, 1450, 1500, 1520, 1580, 1660, 1720, 1800, 1750, 1600, 1580, 1620, 1700, 1750, 1800, 1850, 1900],
    [1100, 1200, 1300, 1400, 1500, 1550, 1480, 1500, 1450, 1380, 1280, 1260, 1300, 1350, 1400, 1450, 1500, 1580, 1600, 1650, 1700, 1680, 1600, 1580, 1520, 1600, 1650, 1700, 1750, 1800],
    [1000, 1050, 1100, 1150, 1200, 1300, 1350, 1400, 1450, 1480, 1500, 1580, 1600, 1620, 1650, 1700, 1750, 1800, 1850, 1890, 1950, 1900, 1850, 1800, 1750, 1780, 1820, 1880, 1900, 1950],
    [1500, 1580, 1620, 1700, 1800, 1900, 1750, 1820, 1850, 1900, 1950, 1980, 2000, 2050, 2100, 2150, 2200, 2250, 2300, 2400, 2500, 2450, 2380, 2300, 2250, 2280, 2320, 2400, 2500, 2600],
    [1800, 1850, 1900, 1950, 2000, 2100, 2050, 2120, 2180, 2200, 2250, 2300, 2350, 2400, 2450, 2500, 2550, 2600, 2650, 2700, 2800, 2750, 2680, 2600, 2550, 2580, 2620, 2700, 2750, 2800],
    [900, 950, 1000, 1050, 1100, 1150, 1200, 1220, 1250, 1280, 1300, 1350, 1380, 1400, 1420, 1450, 1500, 1520, 1550, 1580, 1600, 1620, 1650, 1700, 1720, 1750, 1780, 1800, 1850, 1900],
    [1300, 1350, 1400, 1450, 1500, 1520, 1550, 1580, 1600, 1650, 1680, 1700, 1720, 1750, 1780, 1800, 1850, 1880, 1900, 1920, 1950, 1980, 2000, 2050, 2100, 2150, 2200, 2250, 2300, 2350],
    [1400, 1450, 1500, 1550, 1600, 1620, 1650, 1680, 1700, 1750, 1780, 1800, 1820, 1850, 1880, 1900, 1950, 1980, 2000, 2050, 2100, 2150, 2180, 2200, 2250, 2300, 2350, 2400, 2450, 2500],
    [1600, 1650, 1700, 1750, 1800, 1850, 1880, 1900, 1950, 1980, 2000, 2050, 2100, 2150, 2180, 2200, 2250, 2300, 2350, 2380, 2400, 2450, 2500, 2550, 2600, 2650, 2700, 2750, 2800, 2850],
    [1700, 1750, 1800, 1850, 1900, 1950, 1980, 2000, 2050, 2100, 2150, 2180, 2200, 2250, 2280, 2300, 2350, 2400, 2450, 2500, 2550, 2600, 2650, 2700, 2750, 2800, 2850, 2900, 2950, 3000],
    [1450, 1500, 1550, 1600, 1650, 1700, 1720, 1750, 1780, 1800, 1850, 1880, 1900, 1920, 1950, 1980, 2000, 2050, 2100, 2150, 2200, 2250, 2300, 2350, 2400, 2450, 2500, 2550, 2600, 2650],
    [1900, 1950, 2000, 2050, 2100, 2150, 2180, 2200, 2250, 2280, 2300, 2350, 2400, 2450, 2480, 2500, 2550, 2600, 2650, 2700, 2750, 2780, 2800, 2850, 2900, 2950, 2980, 3000, 3050, 3100]
])
print(np.sum(sales))
print(np.max(sales))
print(np.min(sales))

701130
3100
900


In [37]:
A = np.array([
    120, 130, 140, 150, 160, 170, 180, 190, 200, 210,
    220, 230, 240, 250, 260, 270, 280, 290, 300, 310,
    320, 330, 340, 350, 360, 370, 380, 390, 400, 410,
    420, 430, 440, 450, 460, 470, 480, 490, 500, 510
])
print(A+15)
print(A*15)

[135 145 155 165 175 185 195 205 215 225 235 245 255 265 275 285 295 305
 315 325 335 345 355 365 375 385 395 405 415 425 435 445 455 465 475 485
 495 505 515 525]
[1800 1950 2100 2250 2400 2550 2700 2850 3000 3150 3300 3450 3600 3750
 3900 4050 4200 4350 4500 4650 4800 4950 5100 5250 5400 5550 5700 5850
 6000 6150 6300 6450 6600 6750 6900 7050 7200 7350 7500 7650]


In [47]:
A=np.arange(1,29).reshape(7,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]]


In [50]:
#Create array with ones and zeros
A=np.zeros((4,4))

B=np.ones((4,4))
print(A)

print(B)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
