In [1]:
! pip install numpy

In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
arr=np.array([10,20,30,40,50,60,70,80,90,100])
print(arr)

[ 10  20  30  40  50  60  70  80  90 100]


In [5]:
arr=np.array([[12,14,16], [11,13,15]])
print(arr)

print(arr[0][0])
print(arr[0][1])
print(arr[0][2])
print(arr[1][0])
print(arr[1][1])
print(arr[1][2])

[[12 14 16]
 [11 13 15]]
12
14
16
11
13
15


In [8]:
# using built in methods
np.zeros((3,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [20]:
arr=np.array([[1,3,6],[5,7,9],[0,6,8]])
print(arr)
print(arr.shape)
print(arr.ndim)

[[1 3 6]
 [5 7 9]
 [0 6 8]]
(3, 3)
2


In [27]:
#aray indexing and slicing
arr=np.array([15,20,30,40,55,80])
print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[-2])

15
80
[20 30 40]
55


In [29]:
# array operations
#element wise operations
a=np.array([1,2,4,8])
b=np.array([8,3,7,9])

print(a+b)
print(a*b)
print(a**b)


[ 9  5 11 17]
[ 8  6 28 72]
[        1         8     16384 134217728]


In [30]:
# mathamatical functions
arr=np.array([12,12,13,14])
print(np.sum(arr))
print(np.average(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.sqrt(arr))

51
12.75
12.75
14
12
[3.46410162 3.46410162 3.60555128 3.74165739]


In [37]:
#Reshaping arreas
arr=np.arange(6)
print(arr)
newarr=arr.reshape(2,3)
print(newarr)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [38]:
# Random number
np.random.rand(5)

array([0.04667998, 0.615285  , 0.94123259, 0.7925789 , 0.44673678])

In [39]:
np.random.randint(1,30,10)

array([ 6, 23, 20, 19, 19,  1, 18,  3, 17,  4])

In [41]:
np.random.randn(4,4)

array([[-0.8249519 , -0.87070705,  0.06814766, -0.30065033],
       [ 0.11096685, -0.81286017,  0.60591123, -0.74619738],
       [-0.44674198,  0.2858815 , -1.38089683,  2.78637945],
       [-0.58800043, -0.73800856, -0.87504989,  1.05721951]])

In [45]:
# comparison and logical operator
arr=np.array([10,20,30,40,50])
print(arr>=30)
print(arr<=30)

print(arr[arr>=30])
print(arr[arr<30])

[False False  True  True  True]
[ True  True  True False False]
[30 40 50]
[10 20]


In [47]:
# copy vs view
a=np.array([1,2,3,4,5])
b=a.copy()

print(a)
print(b)

print(b[0])
b[0]=10
print(b[0])

print(b)



[1 2 3 4 5]
[1 2 3 4 5]
1
10
[10  2  3  4  5]


In [49]:
import numpy as np
arr=np.array([10,20,30,40,50,])
print("1d array value ", arr)

1d array value  [10 20 30 40 50]


In [50]:
import numpy as np

arr=np.array([[1,2,3,],[4,5,6,]])
print("2d array value/n ", arr)

2d array value/n  [[1 2 3]
 [4 5 6]]
